# Generated by Django 3.1.5 on 2021-01-14 01:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.CharField(max_length=20)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('guid', models.UUIDField(primary_key=True, serialize=False)),
                ('talkid', models.IntegerField(unique=True)),
                ('abstract', models.TextField()),
                ('date', models.DateTimeField()),
                ('duration', models.IntegerField()),
                ('language', models.CharField(choices=[('en', 'Englisch'), ('de', 'Deutsch')], max_length=2)),
                ('persons', models.TextField()),
                ('room', models.CharField(blank=True, max_length=100)),
                ('track', models.CharField(blank=True, max_length=100)),
                ('url', models.URLField(blank=True)),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.conference')),
            ],
        ),
    ]
