# Generated by Django 3.1.5 on 2021-01-14 02:02

from django.db import migrations, models
import event.models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_event_videofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='videofile',
            field=models.FileField(blank=True, max_length=1000, upload_to=event.models.Event.upload_path),
        ),
    ]
