# Generated by Django 3.1.5 on 2021-01-14 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0007_auto_20210114_0210'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=40),
        ),
    ]
