# Generated by Django 2.2.17 on 2021-01-14 05:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('event', '0008_event_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conference',
            name='owner',
        ),
        migrations.AddField(
            model_name='conference',
            name='owner',
            field=models.ManyToManyField(null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
