# Generated by Django 2.2.17 on 2021-01-14 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0010_auto_20210114_0616'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conference',
            old_name='owner',
            new_name='admins',
        ),
    ]
