# Generated by Django 2.2.17 on 2021-01-14 05:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0011_auto_20210114_0617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conference',
            name='admins',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
