# Generated by Django 2.2.17 on 2021-01-14 06:11

from django.db import migrations, models
import event.models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0012_auto_20210114_0619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='videofile',
            field=models.FileField(max_length=1000, upload_to=event.models.Event.upload_path),
        ),
    ]
