# Generated by Django 2.2.17 on 2021-01-21 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0014_auto_20210114_0745'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='tracker_project_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
