# Generated by Django 2.2.19 on 2021-04-11 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0015_auto_20210121_2156'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='voctoweb_host',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Voctoweb Host (Default: Use tracker project property)'),
        ),
        migrations.AddField(
            model_name='conference',
            name='voctoweb_path',
            field=models.CharField(max_length=200, null=True, verbose_name='Voctoweb Path'),
        ),
        migrations.AddField(
            model_name='conference',
            name='voctoweb_slug',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Voctoweb Slug (Default: Use conference slug)'),
        ),
        migrations.AddField(
            model_name='conference',
            name='voctoweb_thumbpath',
            field=models.CharField(max_length=200, null=True, verbose_name='Voctoweb Thumbpath'),
        ),
        migrations.AddField(
            model_name='conference',
            name='youtube_playlist',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='YouTube Playlist ID (Default: No playlist)'),
        ),
        migrations.AddField(
            model_name='conference',
            name='youtube_token',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='YouTube Token (Default: Disable YouTube Upload)'),
        ),
        migrations.AlterField(
            model_name='conference',
            name='tracker_project_id',
            field=models.IntegerField(default=312),
        ),
    ]
