# Generated by Django 2.2.19 on 2021-04-11 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0016_auto_20210411_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conference',
            name='voctoweb_path',
            field=models.CharField(max_length=200, null=True, verbose_name='Voctoweb Path (e.g. /cdn.media.ccc.de/contributors/myCoolName/)'),
        ),
        migrations.AlterField(
            model_name='conference',
            name='voctoweb_thumbpath',
            field=models.CharField(max_length=200, null=True, verbose_name='Voctoweb Thumbpath (e.g. /static.media.ccc.de/contributors/myCoolName/)'),
        ),
    ]
