# Generated by Django 2.2.19 on 2021-04-11 23:25

from django.db import migrations, models
import event.models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0017_auto_20210411_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='talkid',
            field=models.IntegerField(default=event.models.new_event_id, unique=True),
        ),
    ]
