# Generated by Django 2.2.19 on 2021-04-12 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0018_auto_20210411_2325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conference',
            name='voctoweb_host',
        ),
        migrations.AlterField(
            model_name='conference',
            name='tracker_project_id',
            field=models.IntegerField(default=362),
        ),
    ]
