# Generated by Django 2.2.19 on 2022-01-08 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0020_event_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='remotevideofile',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='language',
            field=models.CharField(choices=[('en', 'Englisch'), ('de', 'Deutsch'), ('de-en', 'Deutsch (+Englisch)'), ('en-de', 'Englisch (+Deutsch)'), ('de-en-fr', 'Deutsch (+Englisch, +Französisch)'), ('de-en-it', 'Deutsch (+Englisch, +Italienisch)'), ('en-de-it', 'Englisch (+Deutsch, +Italienisch)'), ('en-de-fr', 'Englisch (+Deutsch, +Französisch)'), ('de-en-es', 'Deutsch (+Englisch, +Spanisch)'), ('en-de-es', 'Englisch (+Deutsch, +Spanisch)')], max_length=10),
        ),
    ]
