# Generated by Django 5.2.1 on 2025-06-03 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0021_auto_20220108_1826"),
    ]

    operations = [
        migrations.AddField(
            model_name="conference",
            name="youtube_category",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "1  - Film & Animation"),
                    (2, "2  - Autos & Vehicles"),
                    (10, "10 - Music"),
                    (15, "15 - Pets & Animals"),
                    (17, "17 - Sports"),
                    (18, "18 - Short Movies"),
                    (19, "19 - Travel & Events"),
                    (20, "20 - Gaming"),
                    (21, "21 - Videoblogging"),
                    (22, "22 - People & Blogs"),
                    (23, "23 - Comedy"),
                    (24, "24 - Entertainment"),
                    (25, "25 - News & Politics"),
                    (26, "26 - Howto & Style"),
                    (27, "27 - Education"),
                    (28, "28 - Science & Technology"),
                    (30, "30 - Movies"),
                    (31, "31 - Anime/Animation"),
                    (32, "32 - Action/Adventure"),
                    (33, "33 - Classics"),
                    (34, "34 - Comedy"),
                    (35, "35 - Documentary"),
                    (36, "36 - Drama"),
                    (37, "37 - Family"),
                    (38, "38 - Foreign"),
                    (39, "39 - Horror"),
                    (40, "40 - Sci-Fi/Fantasy"),
                    (41, "41 - Thriller"),
                    (42, "42 - Shorts"),
                    (43, "43 - Shows"),
                    (44, "44 - Trailers"),
                ],
                null=True,
                verbose_name="YouTube Category ID",
            ),
        ),
        migrations.AddField(
            model_name="conference",
            name="youtube_privacy",
            field=models.CharField(
                blank=True,
                choices=[
                    ("private", "Private"),
                    ("public", "Public"),
                    ("unlisted", "Unlisted"),
                ],
                max_length=30,
                null=True,
                verbose_name="YouTube Privacy",
            ),
        ),
    ]
